[access_point] # This is the WIFI network that the oscilloscope will create.
ssid = "Oscilloscope"
auth_method = "WPA"
password = "incrediblysecurepassword"

[station] # This is the WIFI network that the oscilloscope will try to connect to.
ssid = "examplesstationssid"
auth_method = "WPA2Personal"
password = "examplesstationpassword"

[voltages]
adc_reference_voltage = 3.1             # Using 11db attenuation.
probe_disconnected = 1.1945787545787547
max_voltage_absolute = 200

[precision]
tolerance_factor = 0.1 # Arbitrary value, filters points from straight lines. Higher value <=> less points.
min_voltage_difference = 0.3 # Needed between two measurements, to be plotted. 
initial_frequency = 10_000_000 # (Hz) Initial frequency for the oscilloscope.